class Game{
  constructor(){this.players=[];this.current=0;this.board=new Board();this.questions=new QuestionManager(this);this.locked=false;this.extraRoll=false;this.finished=false}
  init(){document.getElementById('startBtn').onclick=()=>this.show('setupScreen');document.querySelectorAll('.player-select button').forEach(b=>b.onclick=()=>this.start(Number(b.dataset.players)));document.getElementById('rollBtn').onclick=()=>this.roll();document.getElementById('restartBtn').onclick=()=>location.reload();document.getElementById('winRestartBtn').onclick=()=>location.reload();document.getElementById('toggleLabelsBtn').onclick=()=>this.board.toggleLabels()}
  show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active')}
  start(total){this.players=[];document.getElementById('piecesLayer').innerHTML='';for(let i=1;i<=total;i++){const p=new Player(i);p.create();this.players.push(p)}this.show('gameScreen');setTimeout(()=>{this.players.forEach(p=>this.board.place(p,true));this.updateUI();this.updateScores();this.log('Partida iniciada. Todos empiezan en casilla 1.')},120)}
  async roll(){if(this.locked||this.finished)return;const player=this.players[this.current];if(player.skipTurns>0){player.skipTurns--;this.log(`${player.name} pierde el turno.`);this.nextTurn();return}this.locked=true;this.setStatus(`${player.name} tira el dado...`);const value=await this.rollDiceAnimation();const from=player.position;let target=from+value;if(target>50){target=50-(target-50);this.log(`${player.name}: dado ${value}. Rebota ${from} → ${target}.`)}else{this.log(`${player.name}: dado ${value}. ${from} → ${target}.`)}await this.board.moveStepByStep(player,target);if(window.magicFX)magicFX.landPuff(player.position,player.id);if(player.position===50){this.win(player);return}await this.resolveLanding(player);if(this.extraRoll){this.extraRoll=false;this.locked=false;this.updateUI();return}this.nextTurn()}
  async rollDiceAnimation(){const btn=document.getElementById('rollBtn');const face=document.getElementById('diceFace');const valueEl=document.getElementById('diceValue');const faces=['⚀','⚁','⚂','⚃','⚄','⚅'];btn.classList.remove('rolling','reveal');void btn.offsetWidth;btn.classList.add('rolling');face.textContent='🎲';valueEl.textContent='...';const sparks=setInterval(()=>{if(window.magicFX)magicFX.burstAtElement(btn,'dice',3)},170);await this.wait(1100);clearInterval(sparks);const value=Math.floor(Math.random()*6)+1;btn.classList.remove('rolling');btn.classList.add('reveal');setTimeout(()=>btn.classList.remove('reveal'),500);face.textContent=faces[value-1];valueEl.textContent=value;if(window.magicFX)magicFX.burstAtElement(btn,'dice',12);return value}
  fx(cell,type){if(window.magicFX)magicFX.burstAtCell(cell,type)}
  async resolveLanding(player){const c=player.position;const r=MAGIC5V_DATA.rules;if(r.death===c){this.fx(c,'death');this.setStatus('💀 Muerte: vuelves a la casilla 1.');this.log(`${player.name} cae en muerte y vuelve directo a la salida.`);await this.wait(650);await this.board.jumpTo(player,1);return}if(r.returnStart===c){this.fx(c,'start');this.setStatus('El Conde te envía a la salida.');this.log(`${player.name} cae en 44 y vuelve directo a la salida.`);await this.wait(650);await this.board.jumpTo(player,1);return}if(r.loseTurn.includes(c)){this.fx(c,'lose');player.skipTurns++;this.setStatus(`${player.name} pierde el siguiente turno.`);this.log(`${player.name} cae en casilla negra ${c}.`);await this.wait(700);return}if(r.diceCells[c]){const to=r.diceCells[c];this.fx(c,'dice');this.setStatus(`🎲 Dados: vas a la casilla ${to} y vuelves a tirar.`);this.log(`${player.name} cae en dados ${c} → ${to}.`);await this.wait(650);await this.board.jumpTo(player,to);this.extraRoll=true;return}if(r.colorJumps[c]){const to=r.colorJumps[c];this.fx(c,'color');this.setStatus(`✨ Color: salto ${c} → ${to}.`);this.log(`${player.name} cae en color ${c} → ${to}.`);await this.wait(650);await this.board.jumpTo(player,to);return}if(r.logoCells.includes(c)){const to=this.board.nextLogo(c);if(to!==c){this.fx(c,'logo');this.setStatus(`🌀 Logo: avanzas hasta el siguiente logo (${to}) y vuelves a tirar.`);this.log(`${player.name} cae en logo ${c} → ${to}.`);await this.wait(650);await this.board.jumpTo(player,to);if(player.position===50){this.win(player);return}this.extraRoll=true;return}}
    const q=this.questions.get(c);if(q){this.setStatus(`${player.name} responde una pregunta.`);await this.questions.ask(player,q);return}this.setStatus(`${player.name} se queda en la casilla ${c}.`);await this.wait(350)}
  nextTurn(){this.current=(this.current+1)%this.players.length;this.locked=false;this.updateUI()}
  updateUI(){const p=this.players[this.current];document.getElementById('turnText').innerHTML=`<span class="turn-chip p${p.id}"></span>${p.name}`;document.querySelectorAll('.piece').forEach(e=>e.classList.remove('active'));if(p.element)p.element.classList.add('active');this.setStatus(`Turno de ${p.name}.`);this.updateScores()}
  updateScores(){document.getElementById('scoreList').innerHTML=this.players.map(p=>`<div class="score-row"><span>${p.name}</span><b>${p.score} pt.</b></div>`).join('')}
  setStatus(t){document.getElementById('statusText').textContent=t}
  log(t){const box=document.getElementById('gameLog');box.insertAdjacentHTML('afterbegin',`<div class="log-entry">${t}</div>`)}
  win(player){this.finished=true;this.locked=true;if(window.magicFX)magicFX.starfall(3600);document.getElementById('winText').textContent=`${player.name} ha llegado a la casilla 50 con ${player.score} punto(s).`;document.getElementById('winModal').classList.remove('hidden');this.log(`🏆 ${player.name} gana la partida.`)}
  wait(ms){return new Promise(r=>setTimeout(r,ms))}
}
